services:

  pagopa-bdi-ingestion:
    container_name: pagopa-bdi-ingestion
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    volumes:
      #import of the directory of the certs for the ssl connection to the mock
      - ./docker/bdi-mock/cert_client:/mnt/secrets-store/:ro
    ports:
      - "8090:8080"
    networks:
      - pagopa-bdi-ingestion-net

  bdi-service-mock:
    container_name: bdi-service-mock
    build:
      context: .
      dockerfile: docker/bdi-mock/Dockerfile.bdi-mock
    ports:
      - "8091:3000"
    networks:
      - pagopa-bdi-ingestion-net

networks:
  pagopa-bdi-ingestion-net:
    driver: bridge