apiVersion: v2
type: application
version: 0.2.0
appVersion: 0.2.0
name: pagopa-accounting-reconciliation-bdi-ingestion
description: Microservice designed to ingest BDI data for the accounting reconciliation project.
dependencies:
  - name: microservice-chart
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    version: 8.0.0
